# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.AppTypeDemographicFilter do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :oneOf
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :oneOf => [LINEMessagingAPI.Model.AppTypeDemographic.t] | nil
  }

  def decode(value) do
    value
  end
end

