# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ButtonsTemplate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :thumbnailImageUrl,
    :imageAspectRatio,
    :imageSize,
    :imageBackgroundColor,
    :title,
    :text,
    :defaultAction,
    :actions
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :thumbnailImageUrl => Uri | nil,
    :imageAspectRatio => String.t | nil,
    :imageSize => String.t | nil,
    :imageBackgroundColor => String.t | nil,
    :title => String.t | nil,
    :text => String.t,
    :defaultAction => LINEMessagingAPI.Model.Action.t | nil,
    :actions => [LINEMessagingAPI.Model.Action.t]
  }

  def decode(value) do
    value
  end
end

