# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CarouselTemplate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :columns,
    :imageAspectRatio,
    :imageSize
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :columns => [LINEMessagingAPI.Model.CarouselColumn.t],
    :imageAspectRatio => String.t | nil,
    :imageSize => String.t | nil
  }

  def decode(value) do
    value
  end
end

