# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CarouselColumn do
  @moduledoc """
  Column object for carousel template.
  """

  @derive JSON.Encoder
  defstruct [
    :thumbnailImageUrl,
    :imageBackgroundColor,
    :title,
    :text,
    :defaultAction,
    :actions
  ]

  @type t :: %__MODULE__{
    :thumbnailImageUrl => Uri | nil,
    :imageBackgroundColor => String.t | nil,
    :title => String.t | nil,
    :text => String.t,
    :defaultAction => LINEMessagingAPI.Model.Action.t | nil,
    :actions => [LINEMessagingAPI.Model.Action.t]
  }

  def decode(value) do
    value
  end
end

