# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CashBackFixedPriceInfoResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :currency,
    :fixedAmount
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :currency => String.t | nil,
    :fixedAmount => integer() | nil
  }

  def decode(value) do
    value
  end
end

