# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CashBackPercentagePriceInfoRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :percentage
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :percentage => integer() | nil
  }

  def decode(value) do
    value
  end
end

