# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ClipboardAction do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :label,
    :clipboardText
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :label => String.t | nil,
    :clipboardText => String.t
  }

  def decode(value) do
    value
  end
end

