# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ClipboardImagemapAction do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :area,
    :clipboardText,
    :label
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :area => LINEMessagingAPI.Model.ImagemapArea.t,
    :clipboardText => String.t,
    :label => String.t | nil
  }

  def decode(value) do
    value
  end
end

