# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ConfirmTemplate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :text,
    :actions
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :text => String.t,
    :actions => [LINEMessagingAPI.Model.Action.t]
  }

  def decode(value) do
    value
  end
end

