# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CouponCashBackRewardRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :priceInfo
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :priceInfo => LINEMessagingAPI.Model.CashBackPriceInfoRequest.t | nil
  }

  def decode(value) do
    value
  end
end

