# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.DatetimePickerAction do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :label,
    :data,
    :mode,
    :initial,
    :max,
    :min
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :label => String.t | nil,
    :data => String.t | nil,
    :mode => String.t | nil,
    :initial => String.t | nil,
    :max => String.t | nil,
    :min => String.t | nil
  }

  def decode(value) do
    value
  end
end

