# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.DiscountExplicitPriceInfoResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :currency,
    :priceAfterDiscount,
    :originalPrice
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :currency => String.t | nil,
    :priceAfterDiscount => integer() | nil,
    :originalPrice => integer() | nil
  }

  def decode(value) do
    value
  end
end

