# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ErrorResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :message,
    :details,
    :sentMessages
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :details => [LINEMessagingAPI.Model.ErrorDetail.t] | nil,
    :sentMessages => [LINEMessagingAPI.Model.SentMessage.t] | nil
  }

  def decode(value) do
    value
  end
end

