# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.Filter do
  @moduledoc """
  Filter for narrowcast
  """

  @derive JSON.Encoder
  defstruct [
    :demographic
  ]

  @type t :: %__MODULE__{
    :demographic => LINEMessagingAPI.Model.DemographicFilter.t | nil
  }

  def decode(value) do
    value
  end
end

