# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.FlexVideo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :url,
    :previewUrl,
    :altContent,
    :aspectRatio,
    :action
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :url => Uri,
    :previewUrl => Uri,
    :altContent => LINEMessagingAPI.Model.FlexComponent.t,
    :aspectRatio => String.t | nil,
    :action => LINEMessagingAPI.Model.Action.t | nil
  }

  def decode(value) do
    value
  end
end

