# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.FlexBubble do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :direction,
    :styles,
    :header,
    :hero,
    :body,
    :footer,
    :size,
    :action
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :direction => String.t | nil,
    :styles => LINEMessagingAPI.Model.FlexBubbleStyles.t | nil,
    :header => LINEMessagingAPI.Model.FlexBox.t | nil,
    :hero => LINEMessagingAPI.Model.FlexComponent.t | nil,
    :body => LINEMessagingAPI.Model.FlexBox.t | nil,
    :footer => LINEMessagingAPI.Model.FlexBox.t | nil,
    :size => String.t | nil,
    :action => LINEMessagingAPI.Model.Action.t | nil
  }

  def decode(value) do
    value
  end
end

