# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.FlexBubbleStyles do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :header,
    :hero,
    :body,
    :footer
  ]

  @type t :: %__MODULE__{
    :header => LINEMessagingAPI.Model.FlexBlockStyle.t | nil,
    :hero => LINEMessagingAPI.Model.FlexBlockStyle.t | nil,
    :body => LINEMessagingAPI.Model.FlexBlockStyle.t | nil,
    :footer => LINEMessagingAPI.Model.FlexBlockStyle.t | nil
  }

  def decode(value) do
    value
  end
end

