# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.FlexSeparator do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :margin,
    :color
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :margin => String.t | nil,
    :color => String.t | nil
  }

  def decode(value) do
    value
  end
end

