# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.GetMembershipSubscriptionResponse do
  @moduledoc """
  A user's membership subscription status
  """

  @derive JSON.Encoder
  defstruct [
    :subscriptions
  ]

  @type t :: %__MODULE__{
    :subscriptions => [LINEMessagingAPI.Model.Subscription.t]
  }

  def decode(value) do
    value
  end
end

