# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.GetAggregationUnitNameListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :customAggregationUnits,
    :next
  ]

  @type t :: %__MODULE__{
    :customAggregationUnits => [String.t],
    :next => String.t | nil
  }

  def decode(value) do
    value
  end
end

