# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ImageCarouselTemplate do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :columns
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :columns => [LINEMessagingAPI.Model.ImageCarouselColumn.t]
  }

  def decode(value) do
    value
  end
end

