# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ImagemapAction do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :area
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :area => LINEMessagingAPI.Model.ImagemapArea.t
  }

  def decode(value) do
    value
  end
end

