# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ImagemapVideo do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :originalContentUrl,
    :previewImageUrl,
    :area,
    :externalLink
  ]

  @type t :: %__MODULE__{
    :originalContentUrl => Uri | nil,
    :previewImageUrl => Uri | nil,
    :area => LINEMessagingAPI.Model.ImagemapArea.t | nil,
    :externalLink => LINEMessagingAPI.Model.ImagemapExternalLink.t | nil
  }

  def decode(value) do
    value
  end
end

