# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ImagemapMessage do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :quickReply,
    :sender,
    :baseUrl,
    :altText,
    :baseSize,
    :actions,
    :video
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :quickReply => LINEMessagingAPI.Model.QuickReply.t | nil,
    :sender => LINEMessagingAPI.Model.Sender.t | nil,
    :baseUrl => Uri,
    :altText => String.t,
    :baseSize => LINEMessagingAPI.Model.ImagemapBaseSize.t,
    :actions => [LINEMessagingAPI.Model.ImagemapAction.t],
    :video => LINEMessagingAPI.Model.ImagemapVideo.t | nil
  }

  def decode(value) do
    value
  end
end

