# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ImageMessage do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :quickReply,
    :sender,
    :originalContentUrl,
    :previewImageUrl
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :quickReply => LINEMessagingAPI.Model.QuickReply.t | nil,
    :sender => LINEMessagingAPI.Model.Sender.t | nil,
    :originalContentUrl => Uri,
    :previewImageUrl => Uri
  }

  def decode(value) do
    value
  end
end

