# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.LocationMessage do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :quickReply,
    :sender,
    :title,
    :address,
    :latitude,
    :longitude
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :quickReply => LINEMessagingAPI.Model.QuickReply.t | nil,
    :sender => LINEMessagingAPI.Model.Sender.t | nil,
    :title => String.t,
    :address => String.t,
    :latitude => float(),
    :longitude => float()
  }

  def decode(value) do
    value
  end
end

