# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.MarkMessagesAsReadRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :chat
  ]

  @type t :: %__MODULE__{
    :chat => LINEMessagingAPI.Model.ChatReference.t
  }

  def decode(value) do
    value
  end
end

