# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.MembershipListResponse do
  @moduledoc """
  List of memberships
  """

  @derive JSON.Encoder
  defstruct [
    :memberships
  ]

  @type t :: %__MODULE__{
    :memberships => [LINEMessagingAPI.Model.Membership.t]
  }

  def decode(value) do
    value
  end
end

