# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.MessageQuotaResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :value
  ]

  @type t :: %__MODULE__{
    :type => LINEMessagingAPI.Model.QuotaType.t,
    :value => integer() | nil
  }

  def decode(value) do
    value
  end
end

