# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.NarrowcastRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :messages,
    :recipient,
    :filter,
    :limit,
    :notificationDisabled
  ]

  @type t :: %__MODULE__{
    :messages => [LINEMessagingAPI.Model.Message.t],
    :recipient => LINEMessagingAPI.Model.Recipient.t | nil,
    :filter => LINEMessagingAPI.Model.Filter.t | nil,
    :limit => LINEMessagingAPI.Model.Limit.t | nil,
    :notificationDisabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

