# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.OperatorDemographicFilter do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :and,
    :or,
    :not
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :and => [LINEMessagingAPI.Model.DemographicFilter.t] | nil,
    :or => [LINEMessagingAPI.Model.DemographicFilter.t] | nil,
    :not => LINEMessagingAPI.Model.DemographicFilter.t | nil
  }

  def decode(value) do
    value
  end
end

