# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.PnpMessagesRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :messages,
    :to,
    :notificationDisabled
  ]

  @type t :: %__MODULE__{
    :messages => [LINEMessagingAPI.Model.Message.t],
    :to => String.t,
    :notificationDisabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

