# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.QuickReplyItem do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :imageUrl,
    :action,
    :type
  ]

  @type t :: %__MODULE__{
    :imageUrl => Uri | nil,
    :action => LINEMessagingAPI.Model.Action.t | nil,
    :type => String.t | nil
  }

  def decode(value) do
    value
  end
end

