# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.QuickReply do
  @moduledoc """
  Quick reply
  """

  @derive JSON.Encoder
  defstruct [
    :items
  ]

  @type t :: %__MODULE__{
    :items => [LINEMessagingAPI.Model.QuickReplyItem.t] | nil
  }

  def decode(value) do
    value
  end
end

