# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.QuotaConsumptionResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :totalUsage
  ]

  @type t :: %__MODULE__{
    :totalUsage => integer()
  }

  def decode(value) do
    value
  end
end

