# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.Recipient do
  @moduledoc """
  Recipient
  """

  @derive JSON.Encoder
  defstruct [
    :type
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil
  }

  def decode(value) do
    value
  end
end

