# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ReplyMessageResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :sentMessages
  ]

  @type t :: %__MODULE__{
    :sentMessages => [LINEMessagingAPI.Model.SentMessage.t]
  }

  def decode(value) do
    value
  end
end

