# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuBulkUnlinkRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :userIds
  ]

  @type t :: %__MODULE__{
    :userIds => [String.t]
  }

  def decode(value) do
    value
  end
end

