# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuBounds do
  @moduledoc """
  Rich menu bounds
  """

  @derive JSON.Encoder
  defstruct [
    :x,
    :y,
    :width,
    :height
  ]

  @type t :: %__MODULE__{
    :x => integer() | nil,
    :y => integer() | nil,
    :width => integer() | nil,
    :height => integer() | nil
  }

  def decode(value) do
    value
  end
end

