# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :size,
    :selected,
    :name,
    :chatBarText,
    :areas
  ]

  @type t :: %__MODULE__{
    :size => LINEMessagingAPI.Model.RichMenuSize.t | nil,
    :selected => boolean() | nil,
    :name => String.t | nil,
    :chatBarText => String.t | nil,
    :areas => [LINEMessagingAPI.Model.RichMenuArea.t] | nil
  }

  def decode(value) do
    value
  end
end

