# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuSize do
  @moduledoc """
  Rich menu size
  """

  @derive JSON.Encoder
  defstruct [
    :width,
    :height
  ]

  @type t :: %__MODULE__{
    :width => integer() | nil,
    :height => integer() | nil
  }

  def decode(value) do
    value
  end
end

