# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuBatchUnlinkOperation do
  @moduledoc """
  Unlink the rich menu for all users linked to the rich menu specified in the `from` property.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :from
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :from => String.t
  }

  def decode(value) do
    value
  end
end

