# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuSwitchAction do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :label,
    :data,
    :richMenuAliasId
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :label => String.t | nil,
    :data => String.t | nil,
    :richMenuAliasId => String.t | nil
  }

  def decode(value) do
    value
  end
end

