# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RichMenuBatchRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :operations,
    :resumeRequestKey
  ]

  @type t :: %__MODULE__{
    :operations => [LINEMessagingAPI.Model.RichMenuBatchOperation.t],
    :resumeRequestKey => String.t | nil
  }

  def decode(value) do
    value
  end
end

