# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RoomUserProfileResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :displayName,
    :userId,
    :pictureUrl
  ]

  @type t :: %__MODULE__{
    :displayName => String.t,
    :userId => String.t,
    :pictureUrl => Uri | nil
  }

  def decode(value) do
    value
  end
end

