# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.RoomMemberCountResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :count
  ]

  @type t :: %__MODULE__{
    :count => integer()
  }

  def decode(value) do
    value
  end
end

