# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.Subscription do
  @moduledoc """
  An array of memberships.
  """

  @derive JSON.Encoder
  defstruct [
    :membership,
    :user
  ]

  @type t :: %__MODULE__{
    :membership => LINEMessagingAPI.Model.SubscribedMembershipPlan.t,
    :user => LINEMessagingAPI.Model.SubscribedMembershipUser.t
  }

  def decode(value) do
    value
  end
end

