# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.SubscriptionPeriodDemographicFilter do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :gte,
    :lt
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :gte => LINEMessagingAPI.Model.SubscriptionPeriodDemographic.t | nil,
    :lt => LINEMessagingAPI.Model.SubscriptionPeriodDemographic.t | nil
  }

  def decode(value) do
    value
  end
end

