# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.TemplateMessage do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :quickReply,
    :sender,
    :altText,
    :template
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :quickReply => LINEMessagingAPI.Model.QuickReply.t | nil,
    :sender => LINEMessagingAPI.Model.Sender.t | nil,
    :altText => String.t,
    :template => LINEMessagingAPI.Model.Template.t
  }

  def decode(value) do
    value
  end
end

