# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.TestWebhookEndpointResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :timestamp,
    :statusCode,
    :reason,
    :detail
  ]

  @type t :: %__MODULE__{
    :success => boolean() | nil,
    :timestamp => DateTime.t,
    :statusCode => integer(),
    :reason => String.t,
    :detail => String.t
  }

  def decode(value) do
    value
  end
end

