# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.TextMessageV2 do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :quickReply,
    :sender,
    :text,
    :substitution,
    :quoteToken
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :quickReply => LINEMessagingAPI.Model.QuickReply.t | nil,
    :sender => LINEMessagingAPI.Model.Sender.t | nil,
    :text => String.t,
    :substitution => %{optional(String.t) => LINEMessagingAPI.Model.SubstitutionObject.t} | nil,
    :quoteToken => String.t | nil
  }

  def decode(value) do
    value
  end
end

