# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.UpdateRichMenuAliasRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :richMenuId
  ]

  @type t :: %__MODULE__{
    :richMenuId => String.t
  }

  def decode(value) do
    value
  end
end

