# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.ValidateMessageRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :messages
  ]

  @type t :: %__MODULE__{
    :messages => [LINEMessagingAPI.Model.Message.t]
  }

  def decode(value) do
    value
  end
end

