# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Api.MessagingApiBlob do
  @moduledoc """
  API calls for all endpoints tagged `MessagingApiBlob`.
  """

  @doc """
  Download image, video, and audio data sent from users.

  ### Parameters

  - `client` (Req.Request.t()): Client to make request with
  - `message_id` (String.t): Message ID of video or audio
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Req.Response.t()}` on success
  - `{:error, Exception.t()}` on failure
  """
  def get_message_content(client, message_id, opts \\ []) do
    Req.request(client,
      method: :get,
      url: "/v2/bot/message/#{message_id}/content"
    )
  end

  @doc """
  Get a preview image of the image or video

  ### Parameters

  - `client` (Req.Request.t()): Client to make request with
  - `message_id` (String.t): Message ID of image or video
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Req.Response.t()}` on success
  - `{:error, Exception.t()}` on failure
  """
  def get_message_content_preview(client, message_id, opts \\ []) do
    Req.request(client,
      method: :get,
      url: "/v2/bot/message/#{message_id}/content/preview"
    )
  end

  @doc """
  Verify the preparation status of a video or audio for getting

  ### Parameters

  - `client` (Req.Request.t()): Client to make request with
  - `message_id` (String.t): Message ID of video or audio
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Req.Response.t()}` on success
  - `{:error, Exception.t()}` on failure
  """
  def get_message_content_transcoding_by_message_id(client, message_id, opts \\ []) do
    Req.request(client,
      method: :get,
      url: "/v2/bot/message/#{message_id}/content/transcoding"
    )
  end

  @doc """
  Download rich menu image.

  ### Parameters

  - `client` (Req.Request.t()): Client to make request with
  - `rich_menu_id` (String.t): ID of the rich menu with the image to be downloaded
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Req.Response.t()}` on success
  - `{:error, Exception.t()}` on failure
  """
  def get_rich_menu_image(client, rich_menu_id, opts \\ []) do
    Req.request(client,
      method: :get,
      url: "/v2/bot/richmenu/#{rich_menu_id}/content"
    )
  end

  @doc """
  Upload rich menu image

  ### Parameters

  - `client` (Req.Request.t()): Client to make request with
  - `rich_menu_id` (String.t): The ID of the rich menu to attach the image to
  - `opts` (keyword): Optional parameters
    - `:body` (String.t): 

  ### Returns

  - `{:ok, Req.Response.t()}` on success
  - `{:error, Exception.t()}` on failure
  """
  def set_rich_menu_image(client, rich_menu_id, opts \\ []) do
    body = Keyword.get(opts, :body)
    Req.request(client,
      method: :post,
      url: "/v2/bot/richmenu/#{rich_menu_id}/content",
      json: body
    )
  end
end
