# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Api.Dummy do
  @moduledoc """
  API calls for all endpoints tagged `Dummy`.
  """

  @doc """
  This is the dummy endpoint to generate the model classes

  ### Parameters

  - `client` (Req.Request.t()): Client to make request with
  - `callback_request` (CallbackRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Req.Response.t()}` on success
  - `{:error, Exception.t()}` on failure
  """
  def callback(client, callback_request, opts \\ []) do
    Req.request(client,
      method: :post,
      url: "/callback",
      json: callback_request
    )
  end
end
