# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.AudienceGroupJob do
  @moduledoc """
  Audience group job
  """

  @derive JSON.Encoder
  defstruct [
    :audienceGroupJobId,
    :audienceGroupId,
    :description,
    :type,
    :jobStatus,
    :failedType,
    :audienceCount,
    :created
  ]

  @type t :: %__MODULE__{
    :audienceGroupJobId => integer() | nil,
    :audienceGroupId => integer() | nil,
    :description => String.t | nil,
    :type => LINEMessagingAPI.Model.AudienceGroupJobType.t | nil,
    :jobStatus => LINEMessagingAPI.Model.AudienceGroupJobStatus.t | nil,
    :failedType => LINEMessagingAPI.Model.AudienceGroupJobFailedType.t | nil,
    :audienceCount => integer() | nil,
    :created => integer() | nil
  }

  def decode(value) do
    value
  end
end

