# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.Audience do
  @moduledoc """
  Audience
  """

  @derive JSON.Encoder
  defstruct [
    :id
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil
  }

  def decode(value) do
    value
  end
end

