# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.AudienceGroup do
  @moduledoc """
  Audience group
  """

  @derive JSON.Encoder
  defstruct [
    :audienceGroupId,
    :type,
    :description,
    :status,
    :failedType,
    :audienceCount,
    :created,
    :requestId,
    :clickUrl,
    :isIfaAudience,
    :permission,
    :createRoute
  ]

  @type t :: %__MODULE__{
    :audienceGroupId => integer() | nil,
    :type => LINEMessagingAPI.Model.AudienceGroupType.t | nil,
    :description => String.t | nil,
    :status => LINEMessagingAPI.Model.AudienceGroupStatus.t | nil,
    :failedType => LINEMessagingAPI.Model.AudienceGroupFailedType.t | nil,
    :audienceCount => integer() | nil,
    :created => integer() | nil,
    :requestId => String.t | nil,
    :clickUrl => Uri | nil,
    :isIfaAudience => boolean() | nil,
    :permission => LINEMessagingAPI.Model.AudienceGroupPermission.t | nil,
    :createRoute => LINEMessagingAPI.Model.AudienceGroupCreateRoute.t | nil
  }

  def decode(value) do
    value
  end
end

