# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CreateImpBasedAudienceGroupResponse do
  @moduledoc """
  Create audience for impression-based retargeting
  """

  @derive JSON.Encoder
  defstruct [
    :audienceGroupId,
    :type,
    :description,
    :created,
    :requestId
  ]

  @type t :: %__MODULE__{
    :audienceGroupId => integer() | nil,
    :type => LINEMessagingAPI.Model.AudienceGroupType.t | nil,
    :description => String.t | nil,
    :created => integer() | nil,
    :requestId => String.t | nil
  }

  def decode(value) do
    value
  end
end

