# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.CreateAudienceGroupResponse do
  @moduledoc """
  Create audience for uploading user IDs (by JSON)
  """

  @derive JSON.Encoder
  defstruct [
    :audienceGroupId,
    :createRoute,
    :type,
    :description,
    :created,
    :permission,
    :expireTimestamp,
    :isIfaAudience
  ]

  @type t :: %__MODULE__{
    :audienceGroupId => integer() | nil,
    :createRoute => String.t | nil,
    :type => LINEMessagingAPI.Model.AudienceGroupType.t | nil,
    :description => String.t | nil,
    :created => integer() | nil,
    :permission => String.t | nil,
    :expireTimestamp => integer() | nil,
    :isIfaAudience => boolean() | nil
  }

  def decode(value) do
    value
  end
end

