# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.GetSharedAudienceDataResponse do
  @moduledoc """
  Get audience data
  """

  @derive JSON.Encoder
  defstruct [
    :audienceGroup,
    :jobs,
    :owner
  ]

  @type t :: %__MODULE__{
    :audienceGroup => LINEMessagingAPI.Model.AudienceGroup.t | nil,
    :jobs => [LINEMessagingAPI.Model.AudienceGroupJob.t] | nil,
    :owner => LINEMessagingAPI.Model.DetailedOwner.t | nil
  }

  def decode(value) do
    value
  end
end

