# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.GetAudienceDataResponse do
  @moduledoc """
  Get audience data
  """

  @derive JSON.Encoder
  defstruct [
    :audienceGroup,
    :jobs,
    :adaccount
  ]

  @type t :: %__MODULE__{
    :audienceGroup => LINEMessagingAPI.Model.AudienceGroup.t | nil,
    :jobs => [LINEMessagingAPI.Model.AudienceGroupJob.t] | nil,
    :adaccount => LINEMessagingAPI.Model.Adaccount.t | nil
  }

  def decode(value) do
    value
  end
end

