# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.AccountLinkEvent do
  @moduledoc """
  Event object for when a user has linked their LINE account with a provider's service account. You can reply to account link events.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :source,
    :timestamp,
    :mode,
    :webhookEventId,
    :deliveryContext,
    :replyToken,
    :link
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :source => WebhookTypeDefinition.Model.Source.t | nil,
    :timestamp => integer(),
    :mode => WebhookTypeDefinition.Model.EventMode.t,
    :webhookEventId => String.t,
    :deliveryContext => WebhookTypeDefinition.Model.DeliveryContext.t,
    :replyToken => String.t | nil,
    :link => WebhookTypeDefinition.Model.LinkContent.t
  }

  def decode(value) do
    value
  end
end

