# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.AttachedModuleContent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :botId,
    :scopes
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :botId => String.t,
    :scopes => [String.t]
  }

  def decode(value) do
    value
  end
end

