# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.BeaconContent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :hwid,
    :type,
    :dm
  ]

  @type t :: %__MODULE__{
    :hwid => String.t,
    :type => String.t,
    :dm => String.t | nil
  }

  def decode(value) do
    value
  end
end

