# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.BeaconEvent do
  @moduledoc """
  Event object for when a user enters the range of a LINE Beacon. You can reply to beacon events.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :source,
    :timestamp,
    :mode,
    :webhookEventId,
    :deliveryContext,
    :replyToken,
    :beacon
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :source => WebhookTypeDefinition.Model.Source.t | nil,
    :timestamp => integer(),
    :mode => WebhookTypeDefinition.Model.EventMode.t,
    :webhookEventId => String.t,
    :deliveryContext => WebhookTypeDefinition.Model.DeliveryContext.t,
    :replyToken => String.t,
    :beacon => WebhookTypeDefinition.Model.BeaconContent.t
  }

  def decode(value) do
    value
  end
end

