# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.ChatControl do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :expireAt
  ]

  @type t :: %__MODULE__{
    :expireAt => integer()
  }

  def decode(value) do
    value
  end
end

