# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.ImageMessageContent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :id,
    :contentProvider,
    :imageSet,
    :quoteToken,
    :markAsReadToken
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => String.t,
    :contentProvider => WebhookTypeDefinition.Model.ContentProvider.t,
    :imageSet => WebhookTypeDefinition.Model.ImageSet.t | nil,
    :quoteToken => String.t,
    :markAsReadToken => String.t | nil
  }

  def decode(value) do
    value
  end
end

