# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.LeftMembers do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :members
  ]

  @type t :: %__MODULE__{
    :members => [WebhookTypeDefinition.Model.UserSource.t]
  }

  def decode(value) do
    value
  end
end

