# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.LinkContent do
  @moduledoc """
  Content of the account link event.
  """

  @derive JSON.Encoder
  defstruct [
    :result,
    :nonce
  ]

  @type t :: %__MODULE__{
    :result => String.t,
    :nonce => String.t
  }

  def decode(value) do
    value
  end
end

