# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.MemberJoinedEvent do
  @moduledoc """
  Event object for when a user joins a group chat or multi-person chat that the LINE Official Account is in.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :source,
    :timestamp,
    :mode,
    :webhookEventId,
    :deliveryContext,
    :replyToken,
    :joined
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :source => WebhookTypeDefinition.Model.Source.t | nil,
    :timestamp => integer(),
    :mode => WebhookTypeDefinition.Model.EventMode.t,
    :webhookEventId => String.t,
    :deliveryContext => WebhookTypeDefinition.Model.DeliveryContext.t,
    :replyToken => String.t,
    :joined => WebhookTypeDefinition.Model.JoinedMembers.t
  }

  def decode(value) do
    value
  end
end

