# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.Mention do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :mentionees
  ]

  @type t :: %__MODULE__{
    :mentionees => [WebhookTypeDefinition.Model.Mentionee.t]
  }

  def decode(value) do
    value
  end
end

