# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.MessageContent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :id
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => String.t
  }

  def decode(value) do
    value
  end
end

