# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.PnpDeliveryCompletionEvent do
  @moduledoc """
  When a request is made to the LINE notification messages API and delivery of the LINE notification message to the user is completed, a dedicated webhook event (delivery completion event) is sent from the LINE Platform to the webhook URL of the bot server.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :source,
    :timestamp,
    :mode,
    :webhookEventId,
    :deliveryContext,
    :delivery
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :source => WebhookTypeDefinition.Model.Source.t | nil,
    :timestamp => integer(),
    :mode => WebhookTypeDefinition.Model.EventMode.t,
    :webhookEventId => String.t,
    :deliveryContext => WebhookTypeDefinition.Model.DeliveryContext.t,
    :delivery => WebhookTypeDefinition.Model.PnpDelivery.t
  }

  def decode(value) do
    value
  end
end

