# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.PostbackContent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :data,
    :params
  ]

  @type t :: %__MODULE__{
    :data => String.t,
    :params => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

