# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.RoomSource do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :userId,
    :roomId
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :userId => String.t | nil,
    :roomId => String.t
  }

  def decode(value) do
    value
  end
end

