# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.Source do
  @moduledoc """
  the source of the event.
  """

  @derive JSON.Encoder
  defstruct [
    :type
  ]

  @type t :: %__MODULE__{
    :type => String.t
  }

  def decode(value) do
    value
  end
end

