# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.StickerMessageContent do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :id,
    :packageId,
    :stickerId,
    :stickerResourceType,
    :keywords,
    :text,
    :quoteToken,
    :quotedMessageId,
    :markAsReadToken
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :id => String.t,
    :packageId => String.t,
    :stickerId => String.t,
    :stickerResourceType => String.t,
    :keywords => [String.t] | nil,
    :text => String.t | nil,
    :quoteToken => String.t,
    :quotedMessageId => String.t | nil,
    :markAsReadToken => String.t | nil
  }

  def decode(value) do
    value
  end
end

