# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.UnsendEvent do
  @moduledoc """
  Event object for when the user unsends a message.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :source,
    :timestamp,
    :mode,
    :webhookEventId,
    :deliveryContext,
    :unsend
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :source => WebhookTypeDefinition.Model.Source.t | nil,
    :timestamp => integer(),
    :mode => WebhookTypeDefinition.Model.EventMode.t,
    :webhookEventId => String.t,
    :deliveryContext => WebhookTypeDefinition.Model.DeliveryContext.t,
    :unsend => WebhookTypeDefinition.Model.UnsendDetail.t
  }

  def decode(value) do
    value
  end
end

