# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.VideoPlayComplete do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :trackingId
  ]

  @type t :: %__MODULE__{
    :trackingId => String.t
  }

  def decode(value) do
    value
  end
end

