# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WebhookTypeDefinition.Model.VideoPlayCompleteEvent do
  @moduledoc """
  Event for when a user finishes viewing a video at least once with the specified trackingId sent by the LINE Official Account.
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :source,
    :timestamp,
    :mode,
    :webhookEventId,
    :deliveryContext,
    :replyToken,
    :videoPlayComplete
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :source => WebhookTypeDefinition.Model.Source.t | nil,
    :timestamp => integer(),
    :mode => WebhookTypeDefinition.Model.EventMode.t,
    :webhookEventId => String.t,
    :deliveryContext => WebhookTypeDefinition.Model.DeliveryContext.t,
    :replyToken => String.t,
    :videoPlayComplete => WebhookTypeDefinition.Model.VideoPlayComplete.t
  }

  def decode(value) do
    value
  end
end

