# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI(Insight).Model.GetFriendsDemographicsResponse do
  @moduledoc """
  Get friend demographics
  """

  @derive JSON.Encoder
  defstruct [
    :available,
    :genders,
    :ages,
    :areas,
    :appTypes,
    :subscriptionPeriods
  ]

  @type t :: %__MODULE__{
    :available => boolean() | nil,
    :genders => [LINEMessagingAPI(Insight).Model.GenderTile.t] | nil,
    :ages => [LINEMessagingAPI(Insight).Model.AgeTile.t] | nil,
    :areas => [LINEMessagingAPI(Insight).Model.AreaTile.t] | nil,
    :appTypes => [LINEMessagingAPI(Insight).Model.AppTypeTile.t] | nil,
    :subscriptionPeriods => [LINEMessagingAPI(Insight).Model.SubscriptionPeriodTile.t] | nil
  }

  def decode(value) do
    value
  end
end

