# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI(Insight).Model.GetStatisticsPerUnitResponse do
  @moduledoc """
  Response object for `get statistics per unit`
  """

  @derive JSON.Encoder
  defstruct [
    :overview,
    :messages,
    :clicks
  ]

  @type t :: %__MODULE__{
    :overview => LINEMessagingAPI(Insight).Model.GetStatisticsPerUnitResponseOverview.t,
    :messages => [LINEMessagingAPI(Insight).Model.GetStatisticsPerUnitResponseMessage.t],
    :clicks => [LINEMessagingAPI(Insight).Model.GetStatisticsPerUnitResponseClick.t]
  }

  def decode(value) do
    value
  end
end

