# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI(Insight).Model.GetStatisticsPerUnitResponseClick do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :seq,
    :url,
    :click,
    :uniqueClick,
    :uniqueClickOfRequest
  ]

  @type t :: %__MODULE__{
    :seq => integer(),
    :url => String.t,
    :click => integer() | nil,
    :uniqueClick => integer() | nil,
    :uniqueClickOfRequest => integer() | nil
  }

  def decode(value) do
    value
  end
end

