# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI(Insight).Model.SubscriptionPeriodTile do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :subscriptionPeriod,
    :percentage
  ]

  @type t :: %__MODULE__{
    :subscriptionPeriod => String.t | nil,
    :percentage => float() | nil
  }

  def decode(value) do
    value
  end
end

