# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ChannelAccessTokenAPI.Model.ChannelAccessTokenKeyIdsResponse do
  @moduledoc """
  Channel access token key IDs
  """

  @derive JSON.Encoder
  defstruct [
    :kids
  ]

  @type t :: %__MODULE__{
    :kids => [String.t]
  }

  def decode(value) do
    value
  end
end

