# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule ChannelAccessTokenAPI.Model.IssueChannelAccessTokenResponse do
  @moduledoc """
  Issued channel access token
  """

  @derive JSON.Encoder
  defstruct [
    :access_token,
    :expires_in,
    :token_type,
    :key_id
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :expires_in => integer(),
    :token_type => String.t,
    :key_id => String.t
  }

  def decode(value) do
    value
  end
end

