# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LIFFServerAPI.Model.AddLiffAppResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :liffId
  ]

  @type t :: %__MODULE__{
    :liffId => String.t
  }

  def decode(value) do
    value
  end
end

