# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LIFFServerAPI.Model.LiffFeatures do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :ble,
    :qrCode
  ]

  @type t :: %__MODULE__{
    :ble => boolean() | nil,
    :qrCode => boolean() | nil
  }

  def decode(value) do
    value
  end
end

