# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LIFFServerAPI.Model.UpdateLiffAppRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :view,
    :description,
    :features,
    :permanentLinkPattern,
    :scope,
    :botPrompt
  ]

  @type t :: %__MODULE__{
    :view => LIFFServerAPI.Model.UpdateLiffView.t | nil,
    :description => String.t | nil,
    :features => LIFFServerAPI.Model.LiffFeatures.t | nil,
    :permanentLinkPattern => String.t | nil,
    :scope => [LIFFServerAPI.Model.LiffScope.t] | nil,
    :botPrompt => LIFFServerAPI.Model.LiffBotPrompt.t | nil
  }

  def decode(value) do
    value
  end
end

