# NOTE: This file is auto generated by OpenAPI Generator unset (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule LINEMessagingAPI.Model.DetachModuleRequest do
  @moduledoc """
  Unlink (detach) the module channel by the operation of the module channel administrator
  """

  @derive JSON.Encoder
  defstruct [
    :botId
  ]

  @type t :: %__MODULE__{
    :botId => String.t | nil
  }

  def decode(value) do
    value
  end
end

